# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EOT",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("eot_number", models.CharField(max_length=100, unique=True)),
                ("original_completion_date", models.DateField()),
                ("requested_completion_date", models.DateField()),
                ("days_requested", models.IntegerField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="SUBMITTED", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eot_requests",
                        to="files.governmentfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eot_requests",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ncr_number", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "specification_breached",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor Defect"),
                            ("MAJOR", "Major Non-Conformance"),
                            ("CRITICAL", "Critical Failure"),
                        ],
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                ("corrective_action_required", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESPONSE_SUBMITTED", "Corrective Action Submitted"),
                            ("VERIFIED", "Verified"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncrs",
                        to="projects.project",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.workpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RFI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rfi_number", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("requested_date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INSPECTION_SCHEDULED", "Inspection Scheduled"),
                            ("INSPECTED", "Inspected"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CLOSED", "Closed"),
                        ],
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfis",
                        to="projects.project",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.workpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("observations", models.TextField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("RETURN", "Return for Correction"),
                        ],
                        default="PASS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="projects.project",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.workpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variation_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "proposed_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estimated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("status", models.CharField(default="SUBMITTED", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variations",
                        to="files.governmentfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
