# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("location", models.CharField(max_length=255)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "sanctioned_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("start_date", models.DateField()),
                ("scheduled_completion_date", models.DateField()),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning Phase"),
                            ("ACTIVE", "Active Execution"),
                            ("AT_RISK", "At Risk / Slow Progress"),
                            ("DELAYED", "Delayed"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed & Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "physical_progress_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "financial_progress_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="authority_projects",
                        to="organizations.organizationnode",
                    ),
                ),
                (
                    "consultant_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultant_projects",
                        to="organizations.organizationnode",
                    ),
                ),
                (
                    "contractor_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contractor_projects",
                        to="organizations.organizationnode",
                    ),
                ),
                (
                    "piu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="piu_projects",
                        to="organizations.organizationnode",
                    ),
                ),
                (
                    "regional_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regional_projects",
                        to="organizations.organizationnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("target_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "weightage_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_achieved", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=100, unique=True)),
                (
                    "letter_of_award_ref",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("agreement_date", models.DateField()),
                ("work_order_date", models.DateField()),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("defect_liability_period_months", models.IntegerField(default=24)),
                (
                    "performance_security_details",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "planned_progress_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "actual_progress_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_packages",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("unit", models.CharField(max_length=20)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sanctioned_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "executed_quantity",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "item_code")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_in_project", models.CharField(max_length=50)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user", "role_in_project")},
            },
        ),
    ]
