# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_number", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("file_type", models.CharField(default="GENERAL", max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent / Immediate"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REGISTERED", "Registered / Diarized"),
                            ("ASSIGNED", "Assigned"),
                            ("UNDER_PROCESS", "Under Process"),
                            ("PENDING_ACTION", "Pending Action"),
                            ("RETURNED", "Returned for Clarification"),
                            ("FORWARDED", "Forwarded"),
                            ("UNDER_CONSULTATION", "Under Parallel Consultation"),
                            ("RECOMMENDED", "Recommended"),
                            (
                                "PENDING_APPROVAL",
                                "Pending Competent Authority Approval",
                            ),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="REGISTERED",
                        max_length=30,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_overdue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_dept_files",
                        to="organizations.department",
                    ),
                ),
                (
                    "current_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="held_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.department",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.office",
                    ),
                ),
                (
                    "originator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="originated_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="government_files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "expected_action",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_dept_movements",
                        to="organizations.department",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sent_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_dept_movements",
                        to="organizations.department",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="received_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="files.governmentfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FileDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED_WITH_CONDITIONS", "Approved with Conditions"),
                            ("RETURNED", "Returned for Clarification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "decision_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="files.governmentfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_in_file", models.CharField(max_length=50)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="files.governmentfile",
                    ),
                ),
            ],
            options={
                "unique_together": {("file", "user")},
            },
        ),
        migrations.CreateModel(
            name="FileNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note_number", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("RECOMMEND_APPROVAL", "Recommend Approval"),
                            ("RECOMMEND_REJECTION", "Recommend Rejection"),
                            ("RECOMMEND_MODIFICATION", "Recommend Modification"),
                            ("NEUTRAL", "For Information / Examination"),
                        ],
                        default="NEUTRAL",
                        max_length=30,
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="authored_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="files.governmentfile",
                    ),
                ),
            ],
            options={
                "ordering": ["note_number"],
                "unique_together": {("file", "note_number")},
            },
        ),
    ]
