# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Progress Report"),
                            ("WEEKLY", "Weekly Progress Report"),
                            ("MONTHLY", "Monthly Progress Report"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "physical_progress_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "financial_progress_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("manpower_count", models.IntegerField(default=0)),
                ("equipment_count", models.IntegerField(default=0)),
                ("work_executed_details", models.TextField()),
                ("issues_encountered", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
