# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_number", models.CharField(max_length=100, unique=True)),
                ("bill_period_start", models.DateField()),
                ("bill_period_end", models.DateField()),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "deductions_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted by Contractor"),
                            ("COMPLETENESS_CHECK", "Document Completeness Check"),
                            ("RETURNED", "Returned for Corrections"),
                            ("MEASUREMENT_VERIFICATION", "Measurement Verification"),
                            ("TECHNICAL_VERIFICATION", "Technical Scrutiny"),
                            ("CERTIFIED", "Engineer Certified"),
                            ("FINANCE_REVIEW", "Finance / Accounts Review"),
                            ("AUTHORITY_APPROVAL", "Competent Authority Sanction"),
                            ("PAYMENT_PROCESSING", "Payment Processing"),
                            ("PAID", "Payment Completed / Paid"),
                            ("REJECTED", "Bill Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "government_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_bill",
                        to="files.governmentfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.bill",
                    ),
                ),
                (
                    "boq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="projects.boqitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("measurement_date", models.DateField()),
                (
                    "previous_quantity",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "cumulative_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "balance_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boq_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="projects.boqitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="projects.project",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
