# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "designation_title",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HQ_ADMIN", "HQ Administrator"),
                            ("REGIONAL_OFFICER", "Regional Officer"),
                            ("PROJECT_DIRECTOR", "Project Director"),
                            ("AUTHORITY_ENGINEER", "Authority / Executive Engineer"),
                            ("SITE_ENGINEER", "Government Site Engineer"),
                            ("FINANCE_OFFICER", "Finance / Accounts Officer"),
                            ("QUALITY_OFFICER", "Quality Officer"),
                            ("CONSULTANT", "Consultant"),
                            ("INDEPENDENT_ENGINEER", "Independent Engineer"),
                            ("CONTRACTOR_ADMIN", "Contractor Administrator"),
                            (
                                "CONTRACTOR_PROJECT_MANAGER",
                                "Contractor Project Manager",
                            ),
                            ("CONTRACTOR_SITE_ENGINEER", "Contractor Site Engineer"),
                            (
                                "CONTRACTOR_PLANNING_ENGINEER",
                                "Contractor Planning Engineer",
                            ),
                            (
                                "CONTRACTOR_BILLING_ENGINEER",
                                "Contractor Billing Engineer",
                            ),
                            ("CONTRACTOR_QA_ENGINEER", "Contractor QA/QC Engineer"),
                            ("SUPER_ADMIN", "System Super Admin"),
                        ],
                        default="PROJECT_DIRECTOR",
                        max_length=40,
                    ),
                ),
                ("is_active_employee", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="organizations.department",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="organizations.office",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="organizations.organizationnode",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
