# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Contract Document"),
                            ("DRAWING", "Engineering Drawing"),
                            ("DPR", "Daily Progress Report"),
                            ("WORK_PROGRAMME", "Work Programme"),
                            ("INSPECTION", "Inspection Report"),
                            ("TEST_REPORT", "Quality Test Report"),
                            ("BILL", "Bill Attachment"),
                            ("MEASUREMENT", "Measurement Sheet"),
                            ("CORRESPONDENCE", "Official Correspondence"),
                            ("APPROVAL", "Sanction / Approval Order"),
                            ("VARIATION", "Variation Document"),
                            ("EOT", "Extension of Time"),
                            ("COMPLETION", "Completion Certificate"),
                        ],
                        default="CORRESPONDENCE",
                        max_length=30,
                    ),
                ),
                ("current_version_number", models.IntegerField(default=1)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="files.governmentfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("file_attachment", models.FileField(upload_to="documents/%Y/%m/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("comments", models.TextField(blank=True, default="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("document", "version_number")},
            },
        ),
    ]
