# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("AUTHORITY", "Government Authority"),
                            ("HQ", "Headquarters"),
                            ("REGIONAL_OFFICE", "Regional Office"),
                            ("PIU", "Project Implementation Unit / Division"),
                            ("CONTRACTOR", "Contractor Organization"),
                            ("CONSULTANT", "Consultant Organization"),
                        ],
                        default="AUTHORITY",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.organizationnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="organizations.organizationnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="organizations.organizationnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "code")},
            },
        ),
    ]
